export const invoiceSchema = {
  billingAddress: {},
  cancelledAt: 'No Data Available',
  cartCost: 0.00,
  createdAt: 'No Data Available',
  hasBeenCancelled: false,
  hasBeenShipped: false,
  cartIsEmpty: true,//orderDetails.cartItems.length > 0,
  cartItems: [],
  orderRefId: 'No Data Available',
  paymentMethod: null,
  promoCode: null,
  shippingAddress: {},
  shippingCost: 0.00,
  showAddressLine2_billing: false,
  showAddressLine2_shipping: false,
  showShippingStatus: false,
  showRefundStatus: false,
  taxCost: 0.00,
  totalCost: 0.00,
  refundStatus: 'No Data Available',
};